---
- hosts: all
  vars:
    - ansible_network_os: nmstate
  tasks:
    - net_l3_interface:
        name: web-bond
        state: present
        ipv4: 192.0.2.11/24
        purge: yes
        debug: yes
